[tool.poetry]
name = "NiaAML-GUI"
version = "0.1.2"
description = ""
authors = ["Luka PeÄnik <lukapecnik96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyQt5 = "^5.15.2"
niaaml = "^1.0.0rc2"
NiaPy = "^2.0.0rc12"
QtAwesome = "^1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
